### ISSUE TITLE
Missing dependency on XlsxWriter

### ISSUE THREAD

**Issue by loleg** [ezwelty/tablecloth#1]
Works great for me! And the template functions very well in LibreOffice Calc (7.4) too. The only difference from Excel is that invalid value alerts do not show the constraint possibilities.

Please add XlsxWriter to your README or dependencies:

`pip install xlsxwriter`

(And of course, in the future it would be nice to also support OpenDocument e.g. via [odfpy](https://github.com/eea/odfpy))

**Comment by ezwelty** [comment]
Thanks @loleg, it is configured as an extra since I plan to also bring in Google Sheets support from existing code. I've updated the installation instructions accordingly:

```sh
pip install "tablecloth[excel] @ git+https://github.com/ezwelty/tablecloth"
```

> The only difference from Excel is that invalid value alerts do not show the constraint possibilities.

Did you try setting setting `tablecloth.excel.write_package_template(..., data_validation=True)`? It is off by default. I (and our data submitters) find the alerts annoying; the constraints are better communicated in the header comments.

**Comment by loleg** [comment]
Thanks, good tip!
